### ISSUE TITLE
[Important] Even with Tor, Brave has a unique fingerprint

### ISSUE THREAD

**Issue by zorbakus** [brave/browser-android-tabs#1121]
Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Windows 10 Pro 64-bit
Settings: HTTPS Everywhere, block ads, no script blocking, block 3-rd party cookies, resist all fingerprinting, shields up

I tested on panopticlick.eff.org with Tor window and... I have a unique fingerprint, with 17 bits of indentifying information. Like, what the hell? Why should I use windows with Tor at all if they don't do the one thing Tor was designed to do?

**Comment by tomlowenthal** [comment]
Looks like you're talking about Brave's desktop browser — this is the repo for the Android version. 

Two comments though. Tor hides your browsing from your ISP, and your IP address from the site. It doesn't guarantee any other anonymity properties. Panopticlick also doesn't quite rate Brave as expected due to some limitations what's possible when building a site like that.
