### ISSUE TITLE
Thank you page (publisher banner)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1131]
When you tip a publisher we should display thank you message after tip sent transition. Currently we just close it.

Desktop
for one time tip
![image](https://user-images.githubusercontent.com/9574457/52998685-325e0400-3424-11e9-8eae-269509ff17c5.png)

for recurring
![image](https://user-images.githubusercontent.com/9574457/52998697-3be76c00-3424-11e9-9a51-ac75c33e32c6.png)

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett @anthonypkeane do we have to do that on Android? I don't see it in our layout.

**Comment by LaurenWags** [comment]
Verified passed on 1.0.87 (BR_7) with Asus Zenfone (x86). 
Encountered https://github.com/brave/browser-android-tabs/issues/1306 while testing.
(don't pay attention to the location of the banner on screen, i had to grab screenshots while it was moving in due to how quickly it goes away)
![1131-monthly](https://user-images.githubusercontent.com/28145373/54236910-2af1be00-44eb-11e9-8dcc-68e9a86cb99c.jpg)
![1131-onetime](https://user-images.githubusercontent.com/28145373/54236918-2d541800-44eb-11e9-9474-5395168be397.jpg)
