### ISSUE TITLE
When n/w is disconnected `Rewards server is not responding` message will not be shown until you click on `Your wallet` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1182]
## Description 
When n/w is disconnected `Uh oh! The Brave Rewards server is not responding ` message will not be shown until you click on `Your wallet` in Brave rewards page.

## Steps to Reproduce 

   1. Clean profile 1.0.81
   2. Enable rewards by clicking on `JOIN REWARDS`
   3. Disconnect VPN/wifi
   4. Click on `claim` 
   5. Close the claim popup by clicking on `x`
   6. Click on `Settings`
   
   

## Actual result: 
1. `Uh oh! The Brave Rewards server is not responding ` popup message will not be shown until you click on `Your wallet` in brave rewards page
2. `Uh oh! The Brave Rewards server is not responding ` popup cuts off the screen
3. Content on brave rewards page is scrollable when the focus is on `Uh oh!...` popup.
4. BR panel keeps showing spinner for BAT display

https://drive.google.com/open?id=1eRJwtWECHSnivO-lCT-HYyEQHEgcrhMJ
## Expected result:
Should be same as desktop
1. `Uh oh! The Brave Rewards server is not responding ` popup should be shown in Brave rewards page without click on `Your wallet`
2. `Uh oh! The Brave Rewards server is not responding ` popup should not cuts off the screen
3. When the focus is on  `Uh oh!... ` popup background page content should not be scrollable
4. BR panel shouldn't show any spinner and should show 0.0 BAT

## Issue reproduces how often: 
Always
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy
   - Android Version: 5.1
   
## Brave version:
1.0.81

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by srirambv** [comment]
Also if you try to join rewards when device is offline it goes into an infinite loop of `Creating Wallet` on the active rewards page. Pull reload brings it back to `Yes, I'm in!` message

**Comment by GeetaSarvadnya** [comment]
@srirambv Yes, even I observed that better log a separate issue for it.

**Comment by srirambv** [comment]
I think we can just this one tracking issue for all network related errors. I just saw the recording and here's my observations

>1\.  `Uh oh! The Brave Rewards server is not responding ` popup message will not be shown until you click on `Your wallet` in brave rewards page

This behaviour seems correct to me. Its a little different than desktop because desktop shows wallet summary on rewards page and immediately shows the error message shown when device is offline. Don't think this is possible on Mobile 
cc: @NejcZdovc 

>2\. `Uh oh! The Brave Rewards server is not responding ` popup should not cuts off the screen

This is not a problem on Pixel. The modal isn't being responsive because of which its getting cut off. This is how it looks on Pixel
![image](https://user-images.githubusercontent.com/17010094/53320157-c6cfd700-38fa-11e9-9113-7d2202dcce1f.png)


>3\. Content on brave rewards page is scrollable when focus is on `Uh oh!...` popup.

This is because the background page is scrollable. This scroll is not for the popup but for the rewards page. I think this is fine

>4\. BR panel keeps showing spinner for BAT display

Not sure about it.

**Comment by NejcZdovc** [comment]
@srirambv that is correct for the first one

**Comment by SergeyZhukovsky** [comment]
Ok looking on the discussion 1,2,3 are good, added a message in the panel as well as #4 https://github.com/brave/browser-android-tabs/commit/5d53eb980d57282a3eb157f87935611d8447da93
