### ISSUE TITLE
Toolbar and URL bar are white in Private Mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#1211]
## Description 
The updated toolbar and URL bar is white in Private Mode

## Expected result:
The updated bars should match the Private Mode design

**Existing Toolbar**
![screenshot from 2019-02-27 09-27-02](https://user-images.githubusercontent.com/7606853/53530177-e8b88d80-3aa3-11e9-9629-06e9b30bf058.png)

**New Toolbar**
![screenshot from 2019-02-27 09-23-54](https://user-images.githubusercontent.com/7606853/53530149-d4749080-3aa3-11e9-822b-d466a782f0c6.png)

@jamesmudgett can you confirm?

**Comment by SergeyZhukovsky** [comment]
That's what we have now. @anthonypkeane does it look good? Or should it be all grey?
![img_20190228_162432](https://user-images.githubusercontent.com/12011303/53599624-9e074600-3b75-11e9-90d0-1b161477b5ac.jpg)

**Comment by anthonypkeane** [comment]
Actually it looks fine to me
@jamesmudgett can you chip in?

**Comment by jamesmudgett** [comment]
Looks fine. The issue here will be getting private mode colors in both the url bar and bottom toolbar. We can update later with the more detail url bar changes seen here: (rounded rectangle vs full rounded corners, other details here https://github.com/brave/browser-android-tabs/issues/992)

![home](https://user-images.githubusercontent.com/318119/53670202-b8e9c100-3c2e-11e9-9221-ea19ae188864.png)
