### ISSUE TITLE
Rewards Summary is not displayed in `Your Wallet` page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1213]
## Description 

Rewards Summary is not displayed in `Your Wallet` page
## Steps to Reproduce 

   1. Clean profile 1.0.83
   2. Enable rewards and claim UGP grants
   3. Add DDG to a-c table
   4. Wait for the auto-contribution process to complete

## Actual result: 
After auto-contribution, rewards summary is not displayed in `Your Wallet` page
![screenshot_2019-03-01-00-12-44](https://user-images.githubusercontent.com/38657976/53589986-c5323780-3bb6-11e9-9b6b-321af1d95644.png)

## Expected result:
Rewards summary should be displayed in `Your Wallet` page

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version? no
   - Beta build? yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.83

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/77d469d7c55b49e5bb64efb9f975a1497f1eecd0

**Comment by LaurenWags** [comment]
Reopening, this is not working with 1.0.88: 

![Screenshot_20190313-101910 (1)](https://user-images.githubusercontent.com/28145373/54286951-2b399a00-457b-11e9-9d74-b90a01ca7145.jpg)

![Screenshot_20190313-101904 (1)](https://user-images.githubusercontent.com/28145373/54286956-2e348a80-457b-11e9-886d-22bb312f3f17.jpg)

**Comment by kjozwiak** [comment]
Ran into the following today as well when QA was going through `1.0.88` before the release. It was a bit confusing seeing data listed under the panel summary but nothing under the `chrome://rewards` summary. Definitely reproducible. As @LaurenWags mentioned above, I think this happens when you accept a grant from the panel instead of `chrome://rewards`. Example of the issue:

![Screenshot_20190314-021757](https://user-images.githubusercontent.com/2602313/54335585-d2601500-45ff-11e9-837e-538aad4ae52f.png)

![Screenshot_20190314-021810](https://user-images.githubusercontent.com/2602313/54335594-d855f600-45ff-11e9-8f02-e19cce4c930c.png)

**Comment by ryanml** [comment]
This is fixed via: https://github.com/brave/browser-android-tabs/commit/a90e0f5743c0afe150674d810654cde00746c3e5

Summary should now display in the scenarios detailed above
cc: @anthonypkeane @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3, BraveModernarm v1.0.90

![Screenshot_2019-05-10-21-31-13](https://user-images.githubusercontent.com/38657976/55894682-2e569300-5bd8-11e9-9788-0e4176f029c9.png)
