### ISSUE TITLE
Offer Advice on SafetyNet Attestation Failure

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#1480]
## Description
When a user's device fails the SafetyNet test, we show an unhelpful message about their device being incompatible. We should consider using the [optional `advice` field](https://developer.android.com/training/safetynet/attestation) to offer a more actionable suggestion to the user.

## Steps to reproduce 
1. Load Brave onto a rooted Android device

(Note: These steps are sufficient for reproducing the issue, but not necessary. The same issue may arise on non-rooted devices as well.)

## Actual result
User is [told](https://github.com/brave/browser-android-tabs/blob/d2c8d393b0008f85f3501acbcb52a1079aff567e/chrome/android/java/strings/strings.xml#L247) _"We're sorry it appears Brave Rewards is not available on your device"_.

## Expected result
User is told why, and perhaps what to do to resolve the issue.

## Issue reproduces how often
Always

## Issue happens on
   - Current Play Store version? Yes
   - Beta build? Yes

## Brave version
1.0.91

**Comment by GustavMarwin** [comment]
What do we prevent by restricting devices that do not pass the SafetyNet flag? Does that mean an Android that doesn't have Google Play Services isn't going to be able to use Brave Rewards?

That would imply that the long term plan to make Brave available on F-Droid would be a watered down version too, I can only assume? Clarification would be great because this is a little detail that means a lot when it comes to the long term strategy. Thanks!

**Comment by tomlowenthal** [comment]
This message is deliberately terse for policy reasons.
