### ISSUE TITLE
Several users reporting Shields/Ad-Blocking no longer working on Android

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#1541]
## Description 
Apologies in advance for the vague nature of this issue but I have more than enough users reporting this to justify filing.

**It seems as though many users on Brave Android are seeing ads appear while browsing.** There may be _some_ of these reports referring to 1p ads, but given the nature of the Play store and volume of tickets and support requests; it's inefficient to troubleshoot issues on the medium and users often require additional explanation surrounding what a 1p ad is vs 3p (and subsequently ask why we allow it and why cant the block them, etc).

**Where are the Ads shown?**
Given the inconsistent/lack of communication between play store users reporting and responding to further troubleshooting questions with support, it's been difficult to organize/track these issues or to get a solid list of example websites. Below I've included any/all sites users have explicitly cited showing ads:
- Youtube -- this one is the most frequently cited and should probably be looked at first given its popularity/daily usage. Pre-roll, in-page, and overlay ads have all been reported. A similar issue is open for desktop ([#3348](https://github.com/brave/brave-browser/issues?utf8=✓&q=is%3Aissue+is%3Aopen+youtube))
- https://gamefaqs.com/
- https://news.tut.by/economics/633209.html
- tribunews.com
- yahho.com
- Xnxx, pornhub.com, other “xxx” related sites
- kissanime (kiss-anime.ws)
- Crunchyroll.com

**What Devices?**
Well, all of them -- that is, this doesn't seem to be limited to any particular device type or OS. **Confirmed** devices this has happened on:

- LGV20, V40
- Samsung Galaxy - 8, 8+, 9, 9+
- Samsung Galaxy Note 4
- Nitro 2
- Google Pixel, Pixel 2
- Xiamoi devices
- Galaxy Tab 3, 4

**Region Based?**
I initially thought that it was either specific to certain regions, or at least specific to users outside of US -- both of these have been proven wrong. Known locales/regions where users seeing ads have **confirmed**:

- US -(specific state) IA, IN, VA, NY, FL, CA
- Japan
- France
- UK
- AU
- Brazil
- Russia

## Issue happens on 
   - Current Play Store version?
Yes

## Device details
(See description)

### Additional information

Other potential causes I've ruled out (for some users anyway but I don't think any of these are the cause of the underlying issue):
- Ad-block is confirmed to be enabled
- Regional ad-block (when applicable) is enabled
- Shields are up

Also, I'm happy to include direct text/screen grabs of user reports here, but it may clutter the issue substantially. However, I'd like to point out that **I've tagged ~100 tickets reporting this behavior**.

I've included some of the (very few) example sites users submitted with attached images for reference:
![image](https://user-images.githubusercontent.com/3299098/57556045-c3a98c00-732a-11e9-92f5-9d69ccd7d14e.png)
![image](https://user-images.githubusercontent.com/3299098/57555730-ed15e800-7329-11e9-8233-b39344cdb222.png)
![image](https://user-images.githubusercontent.com/3299098/57556017-ad9bcb80-732a-11e9-80a8-59476adf504e.png)

**Comment by anthonypkeane** [comment]
May be linked to: https://twitter.com/_mauriciorubio/status/1126047628242800640?s=12

**Comment by Brave-Matt** [comment]
Also have this thread going on Community (+1):
https://community.brave.com/t/youtube-ads-not-getting-blocked-by-shields-desktop-mobile/45671

**Comment by samartnik** [comment]
@srirambv @kjozwiak guys did you try it? do we have steps to reproduce?

**Comment by srirambv** [comment]
I can reproduce on Yahoo but not on YouTube.

Just need to open yahoo page and scroll down. and it shows a video ad. There was some discussion about the page using a first party script which is causing the third party ad to show up.
![Screenshot_20190516-122018](https://user-images.githubusercontent.com/17010094/57870420-0ceb5700-77d5-11e9-9c01-940413e2314d.png)

**Comment by Brave-Matt** [comment]
Strangely , I actually can't get YouTube ads to appear _at all_. Both Shields down and `Ad-block` setting unchecked in `Settings --> Privacy -->Ad-block`:
![adstest](https://user-images.githubusercontent.com/3299098/57967360-a2d8cc00-7912-11e9-957c-a1e783c10386.gif)

**Comment by kjozwiak** [comment]
> There was some discussion about the page using a first party script which is causing the third party ad to show up.

Regarding the Yahoo ads, I run into these all the time while going through Yahoo news. The ads look like they're coming from `https://beap.gemini.yahoo.com/` but @lukemulks looked into it and mentioned that was coming from a 3P and was being redirected.

@lukemulks does that sound about right? Can you add your findings regarding the Yahoo ads in here?

**Comment by DoubleYouGTT** [comment]
I'd like to add Google itself to the list of websites that display ads. Shields on or off does not matter.
![Screenshot_2019-06-16-09-40-36](https://user-images.githubusercontent.com/15901992/59561012-e4948980-901a-11e9-9a8e-6a9d52f08971.png)

Brave version: 1.0.97, Chromium 75.0.3770.67
OS: Android 8.0.0, LM-G710 Build/OPR1.170623.032
Device: LG G7 Thinq (model LM-G710EM)
Based in The Netherlands.

**Comment by kjozwiak** [comment]
@DoubleYouGTT the above is expected as we currently don't block first party ads and currently don't have options for cosmetic filters yet.

**Comment by Brave-Matt** [comment]
+1 From reddit:
https://www.reddit.com/r/brave_browser/comments/c68tqz/ads_showing_everywhere_on_mobile/
![image](https://user-images.githubusercontent.com/3299098/60300086-0b887080-98e3-11e9-96c6-511f84d5889f.png)

**Comment by ryder203** [comment]
> @DoubleYouGTT the above is expected as we currently don't block first party ads and currently don't have options for cosmetic filters yet.

No disrespect intended, but clear critique: those Google ads when searching with Google are annoying as they often do not even give good results. The search results are great (well, it's Google), but the ads are bad.

So, if brave is not able to block those ads, I will go back to use **[bromite](https://www.bromite.org/)** on Android, which is in some points even the cooler alternative regarding a chromium based browser running Android.

As Google annunced they change the API that is used by µBlock, I switched to brave on my Windows PC. It is a good browser, but only because µBlock does its job so well.

Conclusion: brave is awesome, I hope it will become even better - but those Google ads... meh!

**Comment by DoubleYouGTT** [comment]
I agree with @ryder203, the reason I switched to Brave was due to privacy and the advertisements that were automatically blocked, plus the future advertisement functionality that Brave itself would provide. Now, if I see advertisements in here, there's tracking information and privacy issues behind those, and that would make the Brave business model (of showing advertisements for personal payment) completely useless, making the Brave browser useless as well and therefore people would easily switch to other options.

Also, I have been using Brave for probably a year now - I forgot when I started with it. I had never seen any ads before using the Brave browser, until recently when I spotted these Google ads (which seemed to have coincided with the Chromium update). As such, due to the significant difference I notice in my Brave user experience, I considered it a bug worth reporting.

**Comment by Brave-Matt** [comment]
+1 from Community
https://community.brave.com/t/ads-on-showing-on-youtube/77941
@anthonypkeane where are we on this?

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/di1gfs/why_am_i_seeing_banner_ads_on_youtube/

**Comment by anthonypkeane** [comment]
This is working now, pls let us know if not
