### ISSUE TITLE
Ads earnings are not instantly updated when opening the Ads panel

### ISSUE THREAD

**Issue by tmancey** [brave/browser-android-tabs#1604]
## Steps to reproduce

   1. Enable Ads
   2. Change Ads Settings > Ads Per Hour to 5
   3. Quit the browser
   4. Launch the browser
   5. Visit www.brave.com
   6. Wait for an Ad notification to be shown (approx. 12 minutes)
   7. Wait a few minutes for the View confirmation to be redeemed
   8. Navigate to chrome://rewards/ads

## Actual result
Ads earnings are not instantly updated to reflect any new earnings, it would appear they are only updated if you are viewing this page when an Ad is confirmed

## Expected result
Ads earnings should be instantly updated to reflect any new earnings.  **See Additional Information below.**

## Issue reproduces how often
Easily reproducible

## Issue happens on 
   - Current Play Store version? No
   - Beta build? No

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone (Pixel3)
   - Android version: 9
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
`this.actions.getTransactionHistoryForThisCycle()` should be called on page load. See https://github.com/brave/browser-android-tabs/blob/base-74.0.3729.136-brave-ads/components/brave_rewards_ui/resources/components/settingsPage.tsx#L75 for current Android implementation

**Comment by LaurenWags** [comment]
Reproduced with Brave_ads2.apk on LG Nexus 5 running Android 5.1.

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible with `Brave_ads2.apk`-  Notifications Received on the Ads panel is Reset to Zero when `chrome://rewards/ads` page is refreshed. STR is mentioned below:

1. Enable Rewards set 5 Ads per hour
2. View a couple of Ads (e.g  3 Ads )
3. Refresh the `chrome://rewards/ads` page
4. Verify that Ads notification received 3 is resets to Zero
5. Wait for 10 mins
6. 4th Ads notification is received, and Ads Panel shows Ads notification received 4
7. Repeat step 3, again ads notification received is resets to Zero

**Comment by srirambv** [comment]
Ran into a different situation. Got an ad. Clicked the notification and landing page opened. Stayed on the page for 10secs or more. Then opened ads details page navigating via chrome://rewards, ads view count is 0, ads earning is 0.00 BAT. Pull down reload the page doesn't refresh the count. 

Device: Huawei P20 running Android 8.1.0
