### ISSUE TITLE
BAT icon is smaller compared to the text 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1620]
## Description 
BAT icon is smaller compared to the text. @yachtcaptain23 likely regressed when resizing icon for Ads

## Actual result 
![Screenshot_20190601-085742](https://user-images.githubusercontent.com/17010094/58749252-b70fe380-8451-11e9-911e-f873ce63dd51.jpg)

## Expected result
Should be properly sized

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 8.1.0
   
## Brave version
Ads build 3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yachtcaptain23** [comment]
I tested this on a Motorola G7 Power, I don't know if this is actually an issue. For me the icon is the same height as `B` and `Brave Rewards` is a single line.

**Comment by rossmoody** [comment]
From what I can tell, the icon is the right size but it appears small because the title is breaking. In this screen is does look like it's breaking prematurely but it's tough to tell without inspecting. Brave UI functionality is this: 

![example](https://user-images.githubusercontent.com/29072694/58984515-1fcac900-878e-11e9-8257-79640bf4275c.gif)

**Comment by tmancey** [comment]
@srirambv please see video above and explanation as to why the icon shrinks, @anthonypkeane @mandar-brave @srirambv are you happy for us to close this as a non issue?

**Comment by anthonypkeane** [comment]
Closing
