### ISSUE TITLE
Notification: Brave Won't run without Google Play Services

### ISSUE THREAD

**Issue by Andrewskiz** [brave/browser-android-tabs#1639]
## Description 
I've been using Brave on Android for some time, but with the newest version I am getting the notification:

> Get Google Play Services
> 
> Brave won't run without Google Play Services, which are missing from your device.

I use Brave and other open source software because I care about privacy and open standards. Is some Google library being used in newer versions of Brave? I've been waiting for Brave to come to the F-Droid app store, but this new development seems like a step in the wrong direction.

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9
   
## Brave version
1.0.95

**Comment by tomlowenthal** [comment]
This notice is correct: Brave relies on Google Play Services. It turns out to be very difficult to run on standard Android builds without using Google Play Services — a separate app/service on the device which handles a lot of common functionality in an efficient way among many apps.

**Comment by thestinger** [comment]
This issue is a newly introduced bug in Chromium. They've consistently resolved these problems in the past, and do consider them to be bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=569285

The newly introduced cause needs to be identified though. It's supposed to safely check for Play Services rather than blindly trying to use it, which ends up triggering this notification. They do the check properly in nearly every case, but there's some new usage without it. This is a problem on devices with Play Services where it's out-of-date, etc. too. This new issue can be triggered by visiting https://www.tomshardware.com/ although the notification will only trigger once. I don't currently have time to look into the cause.

**Comment by tomlowenthal** [comment]
If they fix it in Chromium, we'll pick up that change pretty quickly.

**Comment by jjakob** [comment]
They supposedly fixed it at https://github.com/bromite/bromite/issues/281 by incorporating some patches from GrapheneOS/Vanadium.

**Comment by thestinger** [comment]
I worked around by disabling an optional feature which already had an internal preference. The feature has a hard dependency on Play Services on Android. If explicitly want to offer Google services, then yes they do depend on Play Services and they cannot work around this by disabling Google service integration. If they don't want to depend on Google services, then I don't see why they would have any dependency on Google services. There is the one exception of Safe Browsing but it has a local database implementation and there's a `safe_browsing_mode=3` compilation option to use that on mobile instead of Play Services.

I'm not particularly interested in helping here when the attitude is to deliberately make the app not work on other operating systems for no real reason, along with spreading misinformation about the necessity for Play Services. After this series of interactions across a few issues, including on Twitter, Brave is a bad actor as far as I'm concerned and isn't welcome to use my patches. It's legally permitted by the license, but I won't appreciate it just as I don't appreciate my code being used by other bad actors but don't forbid it in the license. I don't appreciate people spreading misinformation and attacks on what I work on and generally going out of the way to make life harder. I was personally misled by people working there too in their conversations with me. They say one thing to promote it and then their actions don't match at all. Got to love an organization claiming they want to collaborate and then going out of the way to shut that down and spread FUD. Reminds me of several other companies with privacy bandwagon products / business models.

**Comment by tomlowenthal** [comment]
If there's something inaccurate here, I'd love to know what I've got wrong
