### ISSUE TITLE
New behaviour for bottom toolbar buttons

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1707]
Buttons on the bottom toolbar needs to be reorganised. 

Home button implementation is currently a little weird. 
- Enable it and close all tabs quits the browser (#490 & #1180)
- Turn off home button, still shows it as disabled in new tab and enabled on pages allowing to tap and load which defeats the purpose of disabling home button in settings(https://github.com/brave/browser-android-tabs/issues/1403#issuecomment-499889826)

There's a good amount of conversation that happened internally regarding the current behaviour of home button and other buttons on bottom toolbar. more details here: https://bravesoftware.slack.com/archives/C0816QH3R/p1560491378106300

Here's my proposal of what would (probably) be the best behaviour(allowing user to customise) and reasons for it
- Only quit browser when exit is selected from hamburger menu
**Reason**: Exit button does the job no need for other actions to mimic this behaviour
- Irrespective of home button enabled/disabled, closing last tab should not quit the browser
**Reason**: Users want to close all tabs and start fresh without having to relaunch the app which is the expected ideal behaviour which we currently dont have
- Replace home button with `New Tab +`button when home button is disabled in settings
**Reason**: If no home page is set, then default home button option is to load newtab page. If setting is disabled instead of having a dead button replace that with newtab button. _Extra customisation_: Long press context menu can be implemented to launch newtab/private tab only when new tab button is shown. Long press on home button should show option to switch to newtab which then automatically turns off home button in settings
- Leave bookmark/search/tabs overview buttons as it is on the bottom toolbar
**Reason**: Easy access to bookmarks and URL bar is heavily requested so better to leave them as it is 

cc: @jamesmudgett @BrendanEich @anthonypkeane @SergeyZhukovsky

**Comment by deeppandya** [comment]
@srirambv i am thinking to start working this issue. so the things you have suggested in initial post, is it still valid ? can you please confirm ?

**Comment by EyanGoldman** [comment]
Here's my take: 
- Only quit browser when exit is selected from hamburger menu
Reason: Exit button does the job no need for other actions to mimic this behaviour
Agreed.
- Irrespective of home button enabled/disabled, closing last tab should not quit the browser
Reason: Users want to close all tabs and start fresh without having to relaunch the app which is the expected ideal behaviour which we currently dont have
Some users may like this. We don't just want to change the existing behavior. Users should definitely be given the option to toggle on/off with default being off. This is all in the ticket relating to this (#1716). 
- Replace home button with New Tab +button when home button is disabled in settings
Reason: If no home page is set, then default home button option is to load newtab page. If setting is disabled instead of having a dead button replace that with newtab button. Extra customisation: Long press context menu can be implemented to launch newtab/private tab only when new tab button is shown. Long press on home button should show option to switch to newtab which then automatically turns off home button in settings
Agreed.
- Leave bookmark/search/tabs overview buttons as it is on the bottom toolbar
Reason: Easy access to bookmarks and URL bar is heavily requested so better to leave them as it is
Agreed.

**Comment by deeppandya** [comment]
@EyanGoldman  for **Replace home button with New Tab +button when home button is disabled** : should i replace the home button with new tab icon when home page is disabled or should it be in the middle of the toolbar ?

**Comment by EyanGoldman** [comment]
Same location as the home button because moving around other buttons could be confusing to users

**Comment by EyanGoldman** [comment]
New behavior for the New Tab Button (NTB):
- No long press functionality
- If user is currently using a private tab and presses the NTB a private tab will open
- If user is currently using a normal tab and presses the NTP a normal tab will open

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T on Android 9.0 running 1.3.0 beta 1 x64 build
  * Verified long-press on NTB has no effect, doesn't bring up any context menu option
  * Verified on normal tab, tabs tray and press NTB opens a new normal tab
  * Verified on private tab, tabs tray and press NTB opens a new private tab
  * Verified on a normal tab, opening a new tab via hamburger menu, opens a new normal tab
  * Verified on a normal tab, opening a new private tab via hamburger menu, opens a new private tab
  * Verified on a private tab, opening a new tab via hamburger menu, opens a new normal tab
  * Verified on a private tab, opening a new private tab via hamburger menu, opens a new private tab
  * Verified disabling bottom nav bar and NTB opens respective tab from where the NTB is pressed
* Disable Home page
  * Verified home button is replaced with NTB when Home page setting is disabled
  * Verified on normal tab, NTB opens a new normal tab
  * Verified on Private tab, NTB opens a new private tab
  * Verified on a new tab page, NTB is disabled and only enabled when a site is visited
