### ISSUE TITLE
webcompat issues after change to rust adblock library - follow up to 1838

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#1907]
## Description 
Some sites aren't loading properly after the change to rust adblock library (#1838).

## Steps to reproduce 
Twitter
   1. Load twitter.com on clean profile.
   2. You are redirected to mobile.twitter.com
   3. Page doesn't load. 

## Actual result 
![Screenshot_20190731-115239](https://user-images.githubusercontent.com/28145373/62227703-6d2c7680-b38a-11e9-80cd-bef184fa7a06.jpg)
If you toggle Block Ads off, page loads properly.

## Expected result
This is how page loads on 1.1.2:
![Screenshot_20190731-115106](https://user-images.githubusercontent.com/28145373/62227769-86cdbe00-b38a-11e9-9073-374a35a021c0.jpg)

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.2.0 Chromium 76.0.3809.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? yes
- Is the issue reproducible on the latest version of Chrome?  n/a

### Additional information
After step 3 I tried changing to desktop version before toggling Block Ads off, but that didn't load properly either:
![Screenshot_20190731-114841](https://user-images.githubusercontent.com/28145373/62227778-8a614500-b38a-11e9-8061-116e0d24881c.jpg)

**Comment by srirambv** [comment]
Paywall shows up on washingtonpost.com
![Screenshot_20190731-124947_Brave](https://user-images.githubusercontent.com/17010094/62241486-3e70c900-b3a7-11e9-8605-1ed7651c388f.jpg)

**Comment by srirambv** [comment]
+1 from @silentBoY-hu  via #1921 on CR76 build

**Comment by samartnik** [comment]
Additional DEPS were updated in `brave-core` https://github.com/brave/brave-core/commit/8bc9703500dc6d2b6ba526fe7f5e09ca3ec293c8

**Comment by srirambv** [comment]
* Verification passed on OnePlus 6T with Android 9 running 1.20 x64
  * Verified visiting twitter.com redirected to mobile.twitter.com and loaded correctly
  * Verified visiting twitter.com/brave redirected to mobile.twitter.com/brave and loaded correctly
  * Verified visiting twitter.com redirected to mobile.twitter.com and selecting Desktop mode redirected to desktop site twitter.com
  * Verified visiting washingtonpost.com and loading an article didn't show paywall
  * Verified sites don't break because of Adblock.
