### ISSUE TITLE
Cap the number of ads allowed in the notification tray

### ISSUE THREAD

**Issue by EyanGoldman** [brave/browser-android-tabs#1932]
Cap the number of ads allowed in the notification tray so that when the user has 4 ads in the tray and a new ad appears, the oldest ad is removed from the tray and the new one is added. 

The behavior should be identical to a FIFO queue.

**Comment by EyanGoldman** [comment]
Similar but not identical to #1644

**Comment by srirambv** [comment]
I don't think we should automatically remove notifications. We should still use Android group notifications as mentioned in #1644. Either we do the default grouping that Android provides or group notifications like Apple does showing how many notifications are grouped in one notification and clicking that expands the list. 

cc: @SergeyZhukovsky @bbondy

**Comment by anthonypkeane** [comment]
Updating the requirement from 4 ads to 3 following: 
https://bravesoftware.slack.com/archives/CJVNBPK9P/p1566508380158900

**Comment by tmancey** [comment]
@gdregalo This will require changes to the API (which me and George will discuss later today)

**Comment by anthonypkeane** [comment]
Can you please focus on capping the number of ads in the notification tray @gdregalo for this upcoming release. (max in 3 FIFO). 

#1, #2 & #3 above can be worked on as separate tickets in upcoming releases. 

Thanks

**Comment by gdregalo** [comment]
Related: https://github.com/brave/browser-android-tabs/issues/1946
It will be fixed after `notification dismissed` event routed and handled when browser is not running.

**Comment by gdregalo** [comment]
This is how it is implemented:
1. we use fifo queue of 3 ad notifications which can be simultaneously posted.
When we post a new ad notification the first one is removed and new one added to the end of the queue.
Since not all platforms allow us to query all presently posted notifications, the fifo queue is persisted between sessions.

2. Since notifications are removed after system reboot or application update, we check if this kind of event happened between browser sessions and clean the queue accordingly.
3. When notification is closed and the browser is off, the broadcast receiver starts the browser in the background mode (without UI). It waits until ads service is initialized. Once it is initialized we start processing all `dismiss` or `click` events.  Then we start a 60 sec timer and browser stays in the background for another minute waiting for other potential events. If no event arrived during this time and user didn't start the browser, we close it.

TODO: 
1.When we programmatically close the first notification in the queue - this action is not registered. Why don't we mark it as timed out, etc.?
(IMO, we shouldn't remove the first notification programmatically but wait until user remove it himself).

Issues found and resolved:
-notification dismissed event wasn't handled if browser is off (issue #);
-notification could not be closed programmatically from ads-service between browser sessions.  

Fixed by PRs:
https://github.com/brave/brave-core/pull/3306
https://github.com/brave/browser-android-tabs/pull/2054

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.4.0 RC3 x64 build
* Verified only 3 ad notifications are stacked in the notification tray
* Verified only the last 3 recent notification is stored/shown in the notification tray
* Verified new notification causes the older notification to be removed from the notification tray
* Verified number of ads shown isn't limited to the number of ads shown in the tray
![image](https://user-images.githubusercontent.com/17010094/65703254-7a947300-e052-11e9-8f3d-28cc5b9f9a12.png)
Last notification from `Smith+Crown Intelligence` removed from the tray when a new notification is shown
![image](https://user-images.githubusercontent.com/17010094/65703371-a6175d80-e052-11e9-992e-49952ae84db7.png)
Full console logs for the entire flow: [Cap3AdsNotifications.txt](https://github.com/brave/browser-android-tabs/files/3658655/Cap3AdsNotifications.txt)
