### ISSUE TITLE
Check Back Soon for Free Token Grant (with Ads enabled) 

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-android-tabs#1940]
## Description 
I have Ads enabled, and received a "Check Back Soon for Free Token Grant" message in the Brave Rewards panel. 

I don't believe this is expected, as I have Brave Ads enabled (if I recall correctly, I should not receive a free token grant with Ads enabled, or in regions where Ads are enabled). 

## Steps to reproduce 

   1. I received a red dot on the BAT icon
   2. When the BR panel was expanded, I observed the free grant message
   3. When I tapped on the Grants button, the free grant message displays over another message, making the message illegible. 

## Actual result 
Grant message
![Screenshot_20190808-173240](https://user-images.githubusercontent.com/8979240/62749884-fab73880-ba12-11e9-8bd2-07fbce1c9a39.png)

Grant message obstructing text when the Grants button is tapped. 
![Screenshot_20190808-183618](https://user-images.githubusercontent.com/8979240/62749890-fdb22900-ba12-11e9-84c2-d569ab5c9914.png)

## Expected result
Should not receive grants message in regions where Ads are available, or when Ads is activated. 

## Issue reproduces how often 
No steps to repro

## Issue happens on 
   - Current Play Store version?
Yes
   - Beta build?
Unsure
## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet):LG G6
   - Android version: 9
   
## Brave version
1.1.2

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Also, from user's perspective, the ads grant is not a grant. It's a reward for their attention. I think, the  rounded button "Grants" on the panel should be removed too.

**Comment by gdregalo** [comment]
Unfortunately, relying only on user's locale it's not possible to find out if a user is eligible for `android(ugp)` grant. 
(https://bravesoftware.slack.com/archives/CJR5902AW/p1566241397002300?thread_ts=1566240232.001400&cid=CJR5902AW)
A locale can be not supported for ads, but region is supported. In this case a user will not receive an  `android(ugp)` grant but still see a message "Check back soon for free token grant". 
Since there is no way at the moment to determine which region a user is in, I think, we need to remove the above message. 

To determine if a user is in ads region we need a back-end api similar to `fastly geo ip`. Mobile devices can change their networks (or use VPN) pretty often, so we need to consider increased load on the backend. The api can be also implemented locally if we load a db with mapping ip to region, similar to https://linux.die.net/man/1/geoip-lookup.

**Comment by gdregalo** [comment]
@anthonypkeane  @mandar-brave 
please confirm removal of `Check back soon for free token grant` message.
We can re-add it back once geoip api is implemented.

**Comment by mandar-brave** [comment]
Please remove "Free token grant" message;  @alexwykoff can we do the same on the desktop!
I think we should give grants but no need for message as such!

@gdregalo we can decide if we should put it back in.

**Comment by anthonypkeane** [comment]
> please confirm removal of `Check back soon for free token grant` message.


Confirming the removal of the `Check back soon for free token grant` message

**Comment by srirambv** [comment]
@gdregalo confirmed that this is merged into 1.3.1 and hence moving the issue from 1.4.0 to 1.3.1

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.3.1-rc.3 on Samsung s7. The "Check Back Soon for Free Token Grant" is no longer shown, even on unsupported regions.
