### ISSUE TITLE
Can not play video & even crash if disable adblock

### ISSUE THREAD

**Issue by tungdx** [brave/browser-android-tabs#211]
Hello, I have built the app from the source code successfully and then I opened this url: http://dantri.com.vn/video-page.htm and got some issues as the following:
1) Video can not play if adblock is enabled
2) If adblock is disabled, after refreshing the page, the app is crashed. Please check the log file.
[crash.txt](https://github.com/brave/browser-android-tabs/files/909803/crash.txt)

Additional information:
1) The issues won't happen with the Brave app on Google Play
2) My Android device is Nexus 6
3) Another website that has same issues http://www.24h.com.vn/video-ban-thang-c297.html

Please tell me how to fix it. Thank you very much & I will appreciate it.

**Comment by SergeyZhukovsky** [comment]
The issue you in debug mode is because of ASSERT check failed in LayoutGeometryMap.cpp:
    ASSERT(enclosingIntRect(layoutObjectMappedResult) ==
               enclosingIntRect(result.boundingBox()) ||
           layoutObjectMappedResult.mayNotHaveExactIntRectRepresentation() ||
           result.boundingBox().mayNotHaveExactIntRectRepresentation());
It is a bug in a webkit, but it looks like noone knows still why does it appear
https://bugs.webkit.org/show_bug.cgi?id=87194

**Comment by tungdx** [comment]
Hi @SergeyZhukovsky It didn't happen on Brave app that downloaded from the Google Play. Just wondering if I need to adjust some config or so to build?

**Comment by SergeyZhukovsky** [comment]
@tungdx release build ignore asserts. That's why. You made a debug version probably. For the release build you have to create another configuration via gn command.
for example
gn args out/DefaultR
Here is a simple gn file configuration for arm processors release build
https://github.com/brave/browser-android-tabs/wiki/Sample-gn-file-for-arm-release
After that you should build that configuration 
ninja -C out/Default chrome_public_apk

**Comment by tungdx** [comment]
Ah, I understood, let me try it, thanks @SergeyZhukovsky
