### ISSUE TITLE
Rewards isn't always enabled via onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#2203]
## Description 
@kjozwiak  mentioned he ran into a scenario where even though enabling rewards via onboarding he saw panel showing enable rewards. @bbondy  ran into this on iOS as well (https://github.com/brave/brave-ios/issues/1700). @gdregalo  had the same issue as well on his device

## Steps to reproduce 

   1. Clean install
   2. Enable rewards via onboarding
   3. Doesn't join rewards, panel shows join rewards

## Actual result 
Rewards isn't always enabled via onboarding

## Expected result
Enable rewards via onboarding

## Issue reproduces how often 
Not sure

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
I can reproduce this pretty often on my `Pixel 2 XL` device running `Android 10`. Sometimes when you quickly run through the onboarding process and tap on `Start Browsing` after choosing to enable Rewards, you'll run into three scenarios:

* `Scenarios #1` --> Tap on the BAT button in the URL right after going through the onboarding process and Rewards will be enabled as expected

* `Scenarios #2` --> Tap on the BAT button in the URL right after going through the onboarding process and you'll notice that that Brave is attempting to create the wallet but the spinner next to `Creating Wallet` keeps animating and Brave never ends up creating a wallet. You'll need to restart the browser and tap on `Join Rewards` again.

* `Scenarios #2` --> Tap on the BAT button in the URL right after going through the onboarding process and you'll get the `Join Rewards` button in the Brave panel even though you agreed to enable Rewards via onboarding.

I'm not sure if the above cases/behaviour is due to network issues but it varies. Sometimes it works pretty well and sometimes it takes a few attempts to actually get Rewards enabled using onboarding.

**Comment by LaurenWags** [comment]
Verified with LG Nexus5 with Android 5.1 running 1.5.0rc2 BraveModernarm.apk. Tested 6x, here is what I observed:
• After tapping on Start Browsing in onboarding, I swiped away the ad since it was covering the BAT logo. Tapped on the BAT logo. Waited 5-10s while Create Wallet spinner was going. Then, that completed and I waited about 5s more for the balance to show 0 BAT. (observed 5x)
• After tapping on Start Browsing in onboarding, I swiped away the ad since it was covering the BAT logo. Tapped on the BAT logo. Waited 5-10s while Create Wallet spinner was going. Once this spinner was done, balance immediately showed 0 BAT. (observed 1x)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 10` using https://github.com/brave/browser-android-tabs/releases/tag/v1.5.0-rc.2.

This definitely has been improved compared to before. After enabling `Rewards` using onboarding, it opted me in and created the wallet without any issues. Before this fix, sometimes it would never create the wallet and I would need myself via the `Rewards` panel even after enabling it via onboarding.

It's also improved greatly when going through a VPN but I did run into the issue once while connected t o Bulgaria. However, it used to happen on almost every other attempt so things have improved greatly.
