### ISSUE TITLE
Image Credit Redirect

### ISSUE THREAD

**Issue by anthonypkeane** [brave/browser-android-tabs#2355]
## Description 

For one of the background images, the one that says Photo by Louis Kim, the photo credit URL does not resolve. The URL used is http://www.louiskimphotography.com
but the actual URL appears to be http://louiskimphotography.com/

it’s a redirect and looks like HTTPS is not in place (thought the site it redirects to is HTTPS)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.6.1 rc1 x64 build
- Verified images with credit for `Louis Kim` gets redirected to `https://peekay.smugmug.com`
- Verified visiting `http://louiskimphotography.com` auto redirects to `https://peekay.smugmug.com
- Verified image credit link opens in the same tab instead of opening a new one
---------
