### ISSUE TITLE
crash when trying to fetch NTP SI from server when NTP SI has empty json on server

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2511]
## Description 
While testing NTP SI with server side changes, QA experienced crashes when attempting to get an empty json from the server.

## Steps to reproduce 

   1. Have NTP SI campaign active
   2. Have Brave open/active
   3. Push empty json to server
   4. Cycle thru tabs, etc

## Actual result 
Crash

## Expected result
No crash

## Issue reproduces how often 
fairly easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.4 RC1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
We also experienced this crash with malformed json.

**Comment by kjozwiak** [comment]
Working with @deeppandya, QA went through the following cases using several different Android devices using `1.5.4 CR: 79.0.3945.136` 

**`Test Case #1`** (Campaign A --> Campaign B)

* install Brave and ensure that `Campaign A` is being displayed on NTP SI tabs
* ensure that Brave is kept in the foreground while `Campaign B` assets are pushed into `Dev`
* After ~5 mins, `Campaign B` assets should be used when opening NTP SI tabs
* ensure that switching to previous tabs that have `Campaign A` assets switch to `Campaign B` assets

Once the above case passes, uninstall/re-install Brave and ensure that `Campaign B` is being used on new installs.

**`Test Case #2`** (Campaign A --> Empty `json` File)

* install Brave and ensure that `Campaign A` is being displayed on NTP SI tabs
* ensure that Brave is kept in the foreground while an empty `photo.json` is pushed into `Dev`
* After ~5 mins, ensure that there's no NTP SI assets being displayed when opening new tabs
* ensure that switching to previous tabs that have `Campaign A` assets switch to normal images

Once the above case passes, uninstall/re-install Brave and ensure that there's no NTP SI assets being displayed when opening new tabs

**`Test Case #3`** (Campaign A --> Empty `json` File --> Campaign B)

* install Brave and ensure that `Campaign A` is being displayed on NTP SI tabs
* ensure that Brave is kept in the foreground while an empty `photo.json` is pushed into `Dev`
* After ~5 mins, ensure that there's no NTP SI assets being displayed when opening new tabs
* ensure that switching to previous tabs that have `Campaign A` assets switch to normal images
* ensure that Brave is kept in the foreground while `Campaign B` assets are pushed into `Dev`
* After ~5 mins, `Campaign B` assets should be used when opening NTP SI tabs

**`Test Case #4`** (Campaign A --> Malformed `json`)

* install Brave and ensure that `Campaign A` is being displayed on NTP SI tabs
* ensure that Brave is kept in the foreground while a malformed `json` file is pushed into `Dev`
* After ~5 mins, ensure that there's no NTP SI assets being displayed when opening new tabs
* While opening NTP tabs, ensure there's no crashes due to the malformed `json` on the server
* ensure that switching to previous tabs that have `Campaign A` assets switch to normal images

Once the above case passes, uninstall/re-install Brave and ensure that there's no NTP SI assets being displayed when opening new tabs. Ensure that Brave doesn't crash due to the malformed

**`Test Case #5`** (Campaign A --> `404` (no data available server side)

* install Brave and ensure that `Campaign A` is being displayed on NTP SI tabs
* ensure that Brave is kept in the foreground while everything is removed from the `Dev` bucket
* After ~5 mins, ensure that there's no NTP SI assets being displayed when opening new tabs
* While opening NTP tabs, ensure there's no crashes due hitting a `404`
* ensure that switching to previous tabs that have `Campaign A` assets switch to normal images

Once the above case passes, uninstall/re-install Brave and ensure that there's no NTP SI assets being displayed when opening new tabs. Ensure that Brave doesn't crash due to the `404`.
