### ISSUE TITLE
unable to update from 1.5.4 to 1.5.5rc1

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#2539]
## Description 
Unable to update from 1.5.4 to 1.5.5rc1.

## Steps to reproduce 

   1. Install 1.5.4 (from GH or GPS)
   2. Add data
   3. Try to update to 1.5.5rc1

## Actual result 
Unable to update
![Screenshot_20200211-154928](https://user-images.githubusercontent.com/28145373/74278184-cdf81c80-4ce6-11ea-9b67-e9bcabccf66e.jpg)

## Expected result
Able to update

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.5rc1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Clean installs work just fine, per discussion in slack just needs a build with an updated version code.

**Comment by Hamburger6** [comment]
I have the same problem as well. Download comes up as corrupt.

**Comment by kjozwiak** [comment]
@Hamburger6 you'll need to wait for a new RC as the one mentioned above was using incorrect versioning hence the above error. We should have new builds available with a few hours.

Just a quick FYI, sometimes the RC's that we publish on https://github.com/brave/browser-android-tabs/releases that haven't been pushed to GPS might have issues as QA is still running through them.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.5rc2 build
- Verified able to upgrade from 1.5.4 -> 1.5.5 RC2 and doesn't corrupt profile
-------
Verification passed on Samsung Tab A with Android 9 running 1.5.5rc2 build
- Verified able to upgrade from 1.5.4 -> 1.5.5 RC2 and doesn't corrupt profile
-------

**Comment by deeppandya** [comment]
Fixed in a new build with different version number

**Comment by Hamburger6** [comment]
Thank you for the information.



On Feb 12, 2020 at 4:21 AM, Sriram <notifications@github.com> wrote:

Verification passed on OnePlus 6T with Android 10 running 1.5.5rc2 build

   - Verified able to upgrade from 1.5.4 -> 1.5.5 RC2 and doesn't corrupt
   profile

------------------------------

Verification passed on Samsung Tab A with Android 9 running 1.5.5rc2 build

   - Verified able to upgrade from 1.5.4 -> 1.5.5 RC2 and doesn't corrupt
   profile

------------------------------

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-android-tabs/issues/2539?email_source=notifications&email_token=AJROUKLNJKX3HFYDVZLGOCLRCO5RTA5CNFSM4KTIJYQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELQBD5I#issuecomment-585110005>,
or unsubscribe
