### ISSUE TITLE
Unblind token fix (merge of PR 4665 into android_80v2)

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2582]
## Description 
Merging of:  https://github.com/brave/brave-core/pull/4665 into `android_80v2`.
Read the PR and original issues for details.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Cherry-picked:
https://github.com/brave/brave-core/commit/21b53fb92cd18d65c5af190e402fa10ada6908e6

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as there's no way for QA to put the wallet into a broken state due to not being able to edit `publisher_info_db` or `preferences` as per the case outlined via https://github.com/brave/brave-core/pull/4602#issue-374155192. Double checked with @SergeyZhukovsky and QA will basically run through rewards via the manual passes and ensure everything is working as expected.

* Manual test run on Android ARM for 1.5.8 #2587
* Manual test run on Android Tab for 1.5.8 #2589
* Manual test run on Android x86 for 1.5.8 #2588
