### ISSUE TITLE
HTTPS Everywhere not reflected correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-android-tabs#352]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
HTTPS everywhere looks like it's on in shields, but the page indicates that it is not on.

**Device Details:**
   - Install Type(ARM, x86): both
   - Device(Phone, Tablet, Phablet): all
   - Android Version:  all
    
**Brave Version:**
1.0.28, 1.0.29(RC1)

**Steps to reproduce:**
    1. (using HTTPS Everywhere on by default) Open new tab and navigate to https-everywhere.badssl.com
    2. Verify HTTPS Everywhere is working (message at bottom of page)
    3. Tap on shields, toggle off HTTPS Everywhere.
    4. Verify HTTPS Everywhere is not working (message at bottom of page)
    5. Tap on shields, toggle shields off.
    6. Verify HTTPS Everywhere is not working (message at bottom of page)
    7. Tap on shields, toggle shields on. Toggle on HTTPS Everywhere.

**Actual Behavior**
Message at bottom of page says that HTTPS Everywhere is not working.

**Expected Behavior**
Message at bottom of page should indicate that HTTPS Everywhere is working

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Mostly

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

![android_https_everywhee](https://user-images.githubusercontent.com/28145373/29323538-382758e2-81af-11e7-9212-1b627704f91e.gif)

**Any related issues:**

**Comment by AlexeyBarabash** [comment]
There is even easier way to see the issue:
1. Open https://https-everywhere.badssl.com/ site
2. Refresh the page 4 times .

**Comment by AlexeyBarabash** [comment]
I have made investigation, is there any chance to have a new request with a new identifier when the browser does HTTPSE work and the server redirects back to http.
1.
I made a simple local server: https page with http image, server redirects https=>http for the image. Tested it with these HTTP codes:
302 "Found"
301 "Moved Permanently"
307 "Temporary Redirect"
303 "See Other"
308 "Permanent Redirect"

in all cases the url_request has been re-used

2. Looked on chromium sources, the places where redirects are processed. There is no way where redirect result causes an issuing  of a new request. The point is
https://github.com/brave/browser-android-tabs/blob/6840c24c766d77ce930f46bafa452d81d5b83a7d/net/url_request/url_request_job.cc#L478

3. Looked on original HTTPSE plugin for Chrome. https://github.com/EFForg/https-everywhere/blob/aec8d89ed830055f15d769dcfeee12bc21088324/chromium/background.js#L274 . It also relies on request identifier.

4. Crome has the protection from redirection loop, https://github.com/brave/browser-android-tabs/blob/6840c24c766d77ce930f46bafa452d81d5b83a7d/net/url_request/url_request_job.cc#L756 , but finally the the resource could not be loaded, for example image will not be displayed. So the protection from redirect loops is still required for HTTPSE to display the page properly.

The PR can be safely merged to master because the protection from redirections can rely on request identifier.
Found two point in sources which could be polished.
