### ISSUE TITLE
rebuild time takes way to long

### ISSUE THREAD

**Issue by lfxc** [brave/browser-android-tabs#401]
first build takes long, which is ok, but making a change and rebuilding using the same build instructions takes about 3 hours.

Am I doing something wrong?  thanks!

**Comment by SergeyZhukovsky** [comment]
Rebuild always takes so long. There are incremental builds you just simply run `ninja` command to build again and it is fast. Why do you rebuild it after each change?

**Comment by lfxc** [comment]
Maybe we are running wrong ninja command?

**Comment by SergeyZhukovsky** [comment]
It doesn't rebuild everything on our side because it uses incremental builds by default. So if you run that before for a debug build `ninja -C out/Default chrome_public_apk`, make some changes and run the same command again, it only builds the changed files and it dependencies, but it doens't rebuild the whole project. Probably you changed that behavior in your gn file by setting that flag to false enable_incremental_javac.

**Comment by lfxc** [comment]
Got it.  Thanks
