### ISSUE TITLE
Incorrect update of shield counters on scrolling menu

### ISSUE THREAD

**Issue by samartnik** [brave/browser-android-tabs#435]
When scrolling Brave shields menu, numbers for counters are shifted.
![device-2017-10-18-163745](https://user-images.githubusercontent.com/30602739/31721695-c2deab34-b422-11e7-9ca6-9f6228d6deed.png)

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/pull/447/commits/22bb6ef8f36b0936c5cc2d3fe517afaa916abf7d

**Comment by LaurenWags** [comment]
@samartnik is the screenshot what the shields should look like?

**Comment by samartnik** [comment]
The look should be the same. Just numbers should be in correct position when you scroll the menu.

**Comment by LaurenWags** [comment]
Test Plan:
Use a device which will not display the entire shields box so that you will have to scroll
Navigate to a site with shields on
View shields (note where numbers are displayed)
Scroll in the shields
Verify shield numbers stay in the correct place.
Repeat for a site with shields off.

cc @samartnik - is this test plan accurate? Anything else you would suggest adding?

**Comment by LaurenWags** [comment]
Unable to verify this one on ARM build, my device screens don't scroll on shields.

**Comment by srirambv** [comment]
Unable to verify on x86
