### ISSUE TITLE
HTTPSE Prevents Connection to Drudge Report

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-android-tabs#516]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When HTTPSE is enabled, Brave attempts to connect to https://drudgereport.com. The connection is promptly closed by the server, as no HTTPS option exists.

**Device Details:**
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version: 
    
**Brave Version:**
1.0.40

**Steps to reproduce:**
    1. Enable HTTPSE
    2. Navigate to Drudge Report\

**Actual Behavior**
Connection is closed.

**Expected Behavior**
Site loads over HTTP instead.

**Is this an issue with Beta build?**
N/A

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Comment by samartnik** [comment]
Could not reproduce with 1.0.43 version.

**Comment by btlechowski** [comment]
Clean install. Typing drudgereport.com into URL field will open http://drudgereport.com

Clean install. Typing drud into URL field will show drudgereport.com suggestion. Choosing that suggestion will open https://drudgereport.com

Both test cases tested with HTTPSE on and off. 

Since there is no problem with HTTPSE. I verify this issue on Samsung s7 (ARM) v1.0.43(RC1)
I will file another issue for the bad suggestion.

**Comment by LaurenWags** [comment]
New issue opened: https://github.com/brave/browser-android-tabs/issues/572
