### ISSUE TITLE
Feature Request: URL bar at the bottom for Brave on Android

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#54]
Reposting issue posted in Laptop by @D0J0P 

First of all, thank you for finally coming out with a full-blown Brave browser for Android. That was much needed.

I would really like it if there was an option to change the URL bar to the bottom, for easier one-handed use. Chrome Dev for Android now has a chrome://flags setting to enable this in the Chrome UI. It would be great if this flag/feature were included in Brave as a feature itself.

**Comment by SergeyZhukovsky** [comment]
I think we will have that soon when the dev channel will be a stable.

**Comment by D0J0P** [comment]
That sounds good, Sergey! 

And I've been using Brave browser on Android for about 3 weeks or so now, maybe a month. So far, it's the smoothest non-Chrome browser I can find, and with adblock too. It's not as feature rich as Habit or Opera Classic, but I kept browser hopping due to a laggy experience and annoying ads. With Brave, at least I can have decent browsing on Android.

**Comment by SergeyZhukovsky** [comment]
that is already in stable channel.
