### ISSUE TITLE
Enable brave for ultra power saving mode

### ISSUE THREAD

**Issue by vairamsvsjdo** [brave/browser-android-tabs#667]
**Did you search for similar issues before submitting this one?**

Yes
**Description:**
Android has option to run apps in ultra power saving mode
Features needed
1.add an ultra power saving mode in browser, to be able to run in gray scale
2. Add app to support ultra power saving mode

**Device Details:**
   - Install Type(ARM, x86):arm
   - Device(Phone, Tablet, Phablet):Samsung note 4
   - Android Version: 6.0.1
    
**Brave Version:**1.0.51

**Steps to reproduce:**
    1.enable ultra power saving mode in settings
    2.add an app to list, whatsapp is available,  Samsung Internet is available,  but not brave
    3.

**Actual Behavior**
See steps to reproduce

**Expected Behavior**
Able to add brave in ultra power saving mode

**Is this an issue with Beta build?**
No, new feature request 

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**

Yes
**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**

Not required 
**Any related issues:**

**Comment by najodleglejszy** [comment]
Ultra power saving mode isn't a stock Android thing, but an additional feature made by Samsung. I'm not 100% sure, but I believe that only Samsung can whitelist apps available in that mode.

**Comment by Grammost** [comment]
@najodleglejszy is right, this is a feature in Samsung's Android versions and apps can only be added by Samsung themselves, or by the user, but only if you have root access and an app like "UPSM Manager" installed. 
Since there's no way the developers can add Brave to the standard list (apart from actually asking Samsung, but it's extremely unlikely that they'll decide to put Brave in the list of usable apps in the Ultra Power Saving Mode, since it's currently far from being as popular as the very few external apps that are allowed, like WhatsApp), I think this issue can be closed.
